'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Reflection

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource_EN
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VBlib.Resource_EN", GetType(Resource_EN).GetTypeInfo.Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EN.
        '''</summary>
        Friend Shared ReadOnly Property _lang() As String
            Get
                Return ResourceManager.GetString("_lang", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERROR.
        '''</summary>
        Friend Shared ReadOnly Property errAnyError() As String
            Get
                Return ResourceManager.GetString("errAnyError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network is required.
        '''</summary>
        Friend Shared ReadOnly Property errNoNet() As String
            Get
                Return ResourceManager.GetString("errNoNet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot get data folder.
        '''</summary>
        Friend Shared ReadOnly Property errNoRoamFolder() As String
            Get
                Return ResourceManager.GetString("errNoRoamFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This functionality is not present on XBox version of Windows.
        '''</summary>
        Friend Shared ReadOnly Property errXBoxNot() As String
            Get
                Return ResourceManager.GetString("errXBoxNot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SmogMeter.
        '''</summary>
        Friend Shared ReadOnly Property manifestAppName() As String
            Get
                Return ResourceManager.GetString("manifestAppName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About service.
        '''</summary>
        Friend Shared ReadOnly Property msgAboutLink() As String
            Get
                Return ResourceManager.GetString("msgAboutLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clean air :).
        '''</summary>
        Friend Shared ReadOnly Property msgAllOk() As String
            Get
                Return ResourceManager.GetString("msgAllOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Environment status changes:.
        '''</summary>
        Friend Shared ReadOnly Property msgAndroidToastTitle() As String
            Get
                Return ResourceManager.GetString("msgAndroidToastTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning valid.
        '''</summary>
        Friend Shared ReadOnly Property msgBurzeValidity() As String
            Get
                Return ResourceManager.GetString("msgBurzeValidity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy.
        '''</summary>
        Friend Shared ReadOnly Property msgCopyDetails() As String
            Get
                Return ResourceManager.GetString("msgCopyDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to As this is first run, you have to enable some data sources first..
        '''</summary>
        Friend Shared ReadOnly Property msgFirstRunGoSetup() As String
            Get
                Return ResourceManager.GetString("msgFirstRunGoSetup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to For API key, please register.
        '''</summary>
        Friend Shared ReadOnly Property msgForAPIkey() As String
            Get
                Return ResourceManager.GetString("msgForAPIkey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to version.
        '''</summary>
        Friend Shared ReadOnly Property msgVersion() As String
            Get
                Return ResourceManager.GetString("msgVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Humidity inside.
        '''</summary>
        Friend Shared ReadOnly Property msgWilgInt() As String
            Get
                Return ResourceManager.GetString("msgWilgInt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Should I disable all Sources outside selected region?.
        '''</summary>
        Friend Shared ReadOnly Property msgWylaczycPozaZasiegiem() As String
            Get
                Return ResourceManager.GetString("msgWylaczycPozaZasiegiem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yes.
        '''</summary>
        Friend Shared ReadOnly Property msgYes() As String
            Get
                Return ResourceManager.GetString("msgYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to In last.
        '''</summary>
        Friend Shared ReadOnly Property resBurzaOkres() As String
            Get
                Return ResourceManager.GetString("resBurzaOkres", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to thunders.
        '''</summary>
        Friend Shared ReadOnly Property resBurzeCount() As String
            Get
                Return ResourceManager.GetString("resBurzeCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Direction.
        '''</summary>
        Friend Shared ReadOnly Property resBurzeDirection() As String
            Get
                Return ResourceManager.GetString("resBurzeDirection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to calculated value.
        '''</summary>
        Friend Shared ReadOnly Property resCalculated() As String
            Get
                Return ResourceManager.GetString("resCalculated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (no live tile).
        '''</summary>
        Friend Shared ReadOnly Property resDeadTile() As String
            Get
                Return ResourceManager.GetString("resDeadTile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property resDlgCancel() As String
            Get
                Return ResourceManager.GetString("resDlgCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Continue.
        '''</summary>
        Friend Shared ReadOnly Property resDlgContinue() As String
            Get
                Return ResourceManager.GetString("resDlgContinue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No.
        '''</summary>
        Friend Shared ReadOnly Property resDlgNo() As String
            Get
                Return ResourceManager.GetString("resDlgNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yes.
        '''</summary>
        Friend Shared ReadOnly Property resDlgYes() As String
            Get
                Return ResourceManager.GetString("resDlgYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot get location (in timely fashion).
        '''</summary>
        Friend Shared ReadOnly Property resErrorGettingPos() As String
            Get
                Return ResourceManager.GetString("resErrorGettingPos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Location service is not available. Do I have a permission?.
        '''</summary>
        Friend Shared ReadOnly Property resErrorNoGPSAllowed() As String
            Get
                Return ResourceManager.GetString("resErrorNoGPSAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to depth.
        '''</summary>
        Friend Shared ReadOnly Property resGlebokosc() As String
            Get
                Return ResourceManager.GetString("resGlebokosc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nearest river.
        '''</summary>
        Friend Shared ReadOnly Property resImgwHydroAllOFF() As String
            Get
                Return ResourceManager.GetString("resImgwHydroAllOFF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All rivers in range.
        '''</summary>
        Friend Shared ReadOnly Property resImgwHydroAllON() As String
            Get
                Return ResourceManager.GetString("resImgwHydroAllON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precip 60 min.
        '''</summary>
        Friend Shared ReadOnly Property resImgwMeteo10minOFF() As String
            Get
                Return ResourceManager.GetString("resImgwMeteo10minOFF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precip 10 min.
        '''</summary>
        Friend Shared ReadOnly Property resImgwMeteo10minON() As String
            Get
                Return ResourceManager.GetString("resImgwMeteo10minON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to rain between 15 and 40 mm / wind gusts between 60 and 90 km / hail below 2 cm.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_burza_1() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_burza_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to rain between 41 and 70 mm / wind gusts between 91 and 110 km/h / hail between 2 and 5 cm.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_burza_2() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_burza_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to wind gusts between 91 and 110 km/h / grad between 2 and 5 cm / rain over 70 mm / wind gusts over 110 km/h / hail over 5 cm.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_burza_3() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_burza_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to between -20 and -25 °C.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_mroz_1() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_mroz_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to between -26 and -30 °C.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_mroz_2() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_mroz_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to poniżej -30 °C.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_mroz_3() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_mroz_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to rain between 25 and 40 mm in 24 hours / snow between 10 and 15 cm in 24 hours.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_opad_1() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_opad_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to rain between 41 and 70 mm in 24 hours / snow between 16 and 30 cm in 24 hours / snow between 10 and 15 cm in 12 hours.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_opad_2() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_opad_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to rain over 70 mm in 24 hours/snow over 30 cm in 24 hours / snow over 15 cm in 12 hours.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_opad_3() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_opad_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to small risk.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_traba_1() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_traba_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to medium risk.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_traba_2() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_traba_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to high risk.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_traba_3() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_traba_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to between 30 and  34 °C.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_upal_1() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_upal_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to between 35 and 38 °C.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_upal_2() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_upal_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to over 38 °C.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_upal_3() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_upal_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to gusts between 70 and 90 km/h.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_wiatr_1() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_wiatr_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to gusts between 91 and 110 km/h.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_wiatr_2() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_wiatr_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to gusts over 110 km/h.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_wiatr_3() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_wiatr_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name of place.
        '''</summary>
        Friend Shared ReadOnly Property resNazwa() As String
            Get
                Return ResourceManager.GetString("resNazwa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (no autostart).
        '''</summary>
        Friend Shared ReadOnly Property resNoAutostart() As String
            Get
                Return ResourceManager.GetString("resNoAutostart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No sensor in range.
        '''</summary>
        Friend Shared ReadOnly Property resNoSensorInRange() As String
            Get
                Return ResourceManager.GetString("resNoSensorInRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Distance:.
        '''</summary>
        Friend Shared ReadOnly Property resOdleglosc() As String
            Get
                Return ResourceManager.GetString("resOdleglosc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Solar wind density.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarAdditSolarWindDensity() As String
            Get
                Return ResourceManager.GetString("resPomiarAdditSolarWindDensity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Solar wind speed.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarAdditSolarWindSpeed() As String
            Get
                Return ResourceManager.GetString("resPomiarAdditSolarWindSpeed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Solar wind temperature.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarAdditSolarWindTemp() As String
            Get
                Return ResourceManager.GetString("resPomiarAdditSolarWindTemp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tstorm.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarBurza() As String
            Get
                Return ResourceManager.GetString("resPomiarBurza", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tstorm.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarBurza_burza() As String
            Get
                Return ResourceManager.GetString("resPomiarBurza_burza", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Frost.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarBurza_mroz() As String
            Get
                Return ResourceManager.GetString("resPomiarBurza_mroz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precip.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarBurza_opad() As String
            Get
                Return ResourceManager.GetString("resPomiarBurza_opad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cyclon.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarBurza_traba() As String
            Get
                Return ResourceManager.GetString("resPomiarBurza_traba", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Heat.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarBurza_upal() As String
            Get
                Return ResourceManager.GetString("resPomiarBurza_upal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wind.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarBurza_wiatr() As String
            Get
                Return ResourceManager.GetString("resPomiarBurza_wiatr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prediction for.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarNoaaKindexPredicted() As String
            Get
                Return ResourceManager.GetString("resPomiarNoaaKindexPredicted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precip.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarOpad() As String
            Get
                Return ResourceManager.GetString("resPomiarOpad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dew point.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarRosa() As String
            Get
                Return ResourceManager.GetString("resPomiarRosa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SolWind density.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarSolarWindDensity() As String
            Get
                Return ResourceManager.GetString("resPomiarSolarWindDensity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SolWind speed.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarSolarWindSpeed() As String
            Get
                Return ResourceManager.GetString("resPomiarSolarWindSpeed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SolWind temp.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarSolarWindTemp() As String
            Get
                Return ResourceManager.GetString("resPomiarSolarWindTemp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Visibility.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarWidocz() As String
            Get
                Return ResourceManager.GetString("resPomiarWidocz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wind.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarWind() As String
            Get
                Return ResourceManager.GetString("resPomiarWind", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cloud cover.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarZachm() As String
            Get
                Return ResourceManager.GetString("resPomiarZachm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 24 hours average.
        '''</summary>
        Friend Shared ReadOnly Property resRAHdailyAvg() As String
            Get
                Return ResourceManager.GetString("resRAHdailyAvg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property resSaveFav() As String
            Get
                Return ResourceManager.GetString("resSaveFav", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sum of all.
        '''</summary>
        Friend Shared ReadOnly Property resSeismicEU_All() As String
            Get
                Return ResourceManager.GetString("resSeismicEU_All", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All.
        '''</summary>
        Friend Shared ReadOnly Property resSeismicEU_DistAll() As String
            Get
                Return ResourceManager.GetString("resSeismicEU_DistAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to monthly home consumpion.
        '''</summary>
        Friend Shared ReadOnly Property resSeismicEU_HomekWh() As String
            Get
                Return ResourceManager.GetString("resSeismicEU_HomekWh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your home monthly consumption.
        '''</summary>
        Friend Shared ReadOnly Property resSeismicEU_HomekWh_Hdr() As String
            Get
                Return ResourceManager.GetString("resSeismicEU_HomekWh_Hdr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to months of country production.
        '''</summary>
        Friend Shared ReadOnly Property resSeismicEU_KrajTWh() As String
            Get
                Return ResourceManager.GetString("resSeismicEU_KrajTWh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your country yearly production.
        '''</summary>
        Friend Shared ReadOnly Property resSeismicEU_KrajTWh_Hdr() As String
            Get
                Return ResourceManager.GetString("resSeismicEU_KrajTWh_Hdr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only one quake (max).
        '''</summary>
        Friend Shared ReadOnly Property resSeismicEU_Max() As String
            Get
                Return ResourceManager.GetString("resSeismicEU_Max", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quake range.
        '''</summary>
        Friend Shared ReadOnly Property resSeismicEU_SldHdr() As String
            Get
                Return ResourceManager.GetString("resSeismicEU_SldHdr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T Αpparent.
        '''</summary>
        Friend Shared ReadOnly Property resTempOdczuwana() As String
            Get
                Return ResourceManager.GetString("resTempOdczuwana", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to altitude.
        '''</summary>
        Friend Shared ReadOnly Property resWysokosc() As String
            Get
                Return ResourceManager.GetString("resWysokosc", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
