'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Reflection

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource_PL
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VBlib.Resource_PL", GetType(Resource_PL).GetTypeInfo.Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PL.
        '''</summary>
        Friend Shared ReadOnly Property _lang() As String
            Get
                Return ResourceManager.GetString("_lang", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Błąd.
        '''</summary>
        Friend Shared ReadOnly Property errAnyError() As String
            Get
                Return ResourceManager.GetString("errAnyError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bez sieci nie da rady.
        '''</summary>
        Friend Shared ReadOnly Property errNoNet() As String
            Get
                Return ResourceManager.GetString("errNoNet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Brak dostępu do katalogu.
        '''</summary>
        Friend Shared ReadOnly Property errNoRoamFolder() As String
            Get
                Return ResourceManager.GetString("errNoRoamFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Windows na XBox nie ma tej funkcjonalności..
        '''</summary>
        Friend Shared ReadOnly Property errXBoxNot() As String
            Get
                Return ResourceManager.GetString("errXBoxNot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Smogometr.
        '''</summary>
        Friend Shared ReadOnly Property manifestAppName() As String
            Get
                Return ResourceManager.GetString("manifestAppName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to O serwisie.
        '''</summary>
        Friend Shared ReadOnly Property msgAboutLink() As String
            Get
                Return ResourceManager.GetString("msgAboutLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Czyste powietrze :).
        '''</summary>
        Friend Shared ReadOnly Property msgAllOk() As String
            Get
                Return ResourceManager.GetString("msgAllOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zmiany stanu środowiska:.
        '''</summary>
        Friend Shared ReadOnly Property msgAndroidToastTitle() As String
            Get
                Return ResourceManager.GetString("msgAndroidToastTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ostrzeżenie na.
        '''</summary>
        Friend Shared ReadOnly Property msgBurzeValidity() As String
            Get
                Return ResourceManager.GetString("msgBurzeValidity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kopiuj.
        '''</summary>
        Friend Shared ReadOnly Property msgCopyDetails() As String
            Get
                Return ResourceManager.GetString("msgCopyDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pierwsze uruchomienie - włącz wybrane źródła danych..
        '''</summary>
        Friend Shared ReadOnly Property msgFirstRunGoSetup() As String
            Get
                Return ResourceManager.GetString("msgFirstRunGoSetup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aby uzyskać API key, zarejestruj się.
        '''</summary>
        Friend Shared ReadOnly Property msgForAPIkey() As String
            Get
                Return ResourceManager.GetString("msgForAPIkey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to wersja.
        '''</summary>
        Friend Shared ReadOnly Property msgVersion() As String
            Get
                Return ResourceManager.GetString("msgVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wilgotność wewnątrz.
        '''</summary>
        Friend Shared ReadOnly Property msgWilgInt() As String
            Get
                Return ResourceManager.GetString("msgWilgInt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Są włączone Źródła danych spoza wybranego obszaru - wyłączyć je?.
        '''</summary>
        Friend Shared ReadOnly Property msgWylaczycPozaZasiegiem() As String
            Get
                Return ResourceManager.GetString("msgWylaczycPozaZasiegiem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tak.
        '''</summary>
        Friend Shared ReadOnly Property msgYes() As String
            Get
                Return ResourceManager.GetString("msgYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to W ostatnich.
        '''</summary>
        Friend Shared ReadOnly Property resBurzaOkres() As String
            Get
                Return ResourceManager.GetString("resBurzaOkres", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to wyładowań.
        '''</summary>
        Friend Shared ReadOnly Property resBurzeCount() As String
            Get
                Return ResourceManager.GetString("resBurzeCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kierunek.
        '''</summary>
        Friend Shared ReadOnly Property resBurzeDirection() As String
            Get
                Return ResourceManager.GetString("resBurzeDirection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to wartość obliczona.
        '''</summary>
        Friend Shared ReadOnly Property resCalculated() As String
            Get
                Return ResourceManager.GetString("resCalculated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (martwe tile).
        '''</summary>
        Friend Shared ReadOnly Property resDeadTile() As String
            Get
                Return ResourceManager.GetString("resDeadTile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to zaniechaj.
        '''</summary>
        Friend Shared ReadOnly Property resDlgCancel() As String
            Get
                Return ResourceManager.GetString("resDlgCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to dalej.
        '''</summary>
        Friend Shared ReadOnly Property resDlgContinue() As String
            Get
                Return ResourceManager.GetString("resDlgContinue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nie.
        '''</summary>
        Friend Shared ReadOnly Property resDlgNo() As String
            Get
                Return ResourceManager.GetString("resDlgNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tak.
        '''</summary>
        Friend Shared ReadOnly Property resDlgYes() As String
            Get
                Return ResourceManager.GetString("resDlgYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nie udało się uzyskać współrzędnych lokalizacji..
        '''</summary>
        Friend Shared ReadOnly Property resErrorGettingPos() As String
            Get
                Return ResourceManager.GetString("resErrorGettingPos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Brak dostępu do usługi lokalizacji. Sprawdź uprawnienia aplikacji..
        '''</summary>
        Friend Shared ReadOnly Property resErrorNoGPSAllowed() As String
            Get
                Return ResourceManager.GetString("resErrorNoGPSAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to głębokość.
        '''</summary>
        Friend Shared ReadOnly Property resGlebokosc() As String
            Get
                Return ResourceManager.GetString("resGlebokosc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Najbliższa rzeka.
        '''</summary>
        Friend Shared ReadOnly Property resImgwHydroAllOFF() As String
            Get
                Return ResourceManager.GetString("resImgwHydroAllOFF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wszystkie rzeki w pobliżu.
        '''</summary>
        Friend Shared ReadOnly Property resImgwHydroAllON() As String
            Get
                Return ResourceManager.GetString("resImgwHydroAllON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opad 60 min.
        '''</summary>
        Friend Shared ReadOnly Property resImgwMeteo10minOFF() As String
            Get
                Return ResourceManager.GetString("resImgwMeteo10minOFF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opad 10 min.
        '''</summary>
        Friend Shared ReadOnly Property resImgwMeteo10minON() As String
            Get
                Return ResourceManager.GetString("resImgwMeteo10minON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to deszcz od 15 do 40 mm / wiatr w porywach od 60 do 90 km/h / grad poniżej 2 cm.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_burza_1() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_burza_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to deszcz od 41 do 70 mm/wiatr w porywach od 91 do 110 km/h / grad od 2 do 5 cm.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_burza_2() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_burza_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to wiatr w porywach od 91 do 110 km/h / grad od 2 do 5 cm / deszcz powyżej 70 mm/wiatr w porywach powyżej 110 km/h / grad powyżej 5 cm.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_burza_3() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_burza_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to od -20 do -25 °C.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_mroz_1() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_mroz_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to od -26 do -30 °C.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_mroz_2() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_mroz_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to poniżej -30 °C.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_mroz_3() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_mroz_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to deszcz od 25 do 40 mm w ciągu 24 godzin / śnieg od 10 do 15 cm w ciągu 24 godzin.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_opad_1() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_opad_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to deszcz od 41 do 70 mm w ciągu 24 godzin / śnieg od 16 do 30 cm w ciągu 24 godzin / śnieg od 10 do 15 cm w ciągu 12 godzin.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_opad_2() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_opad_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to deszcz powyżej 70 mm w ciągu 24 godzin / śnieg powyżej 30 cm w ciągu 24 godzin / śnieg powyżej 15 cm w ciągu 12 godzin.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_opad_3() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_opad_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ryzyko niewielkie.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_traba_1() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_traba_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ryzyko umiarkowane.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_traba_2() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_traba_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ryzyko wysokie.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_traba_3() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_traba_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to od 30 do 34 °C.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_upal_1() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_upal_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to od 35 do 38 °C.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_upal_2() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_upal_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to powyżej 38 °C.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_upal_3() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_upal_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to w porywach od 70 do 90 km/h.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_wiatr_1() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_wiatr_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to w porywach od 91 do 110 km/h.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_wiatr_2() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_wiatr_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to w porywach powyżej 110 km/h.
        '''</summary>
        Friend Shared ReadOnly Property resLimitBurza_wiatr_3() As String
            Get
                Return ResourceManager.GetString("resLimitBurza_wiatr_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nazwa miejsca.
        '''</summary>
        Friend Shared ReadOnly Property resNazwa() As String
            Get
                Return ResourceManager.GetString("resNazwa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (bez autoload).
        '''</summary>
        Friend Shared ReadOnly Property resNoAutostart() As String
            Get
                Return ResourceManager.GetString("resNoAutostart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nie znalazłem żadnego czujnika w okolicy.
        '''</summary>
        Friend Shared ReadOnly Property resNoSensorInRange() As String
            Get
                Return ResourceManager.GetString("resNoSensorInRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Odl:.
        '''</summary>
        Friend Shared ReadOnly Property resOdleglosc() As String
            Get
                Return ResourceManager.GetString("resOdleglosc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gęstość wiatru słonecznego.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarAdditSolarWindDensity() As String
            Get
                Return ResourceManager.GetString("resPomiarAdditSolarWindDensity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Szybkość wiatru słonecznego.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarAdditSolarWindSpeed() As String
            Get
                Return ResourceManager.GetString("resPomiarAdditSolarWindSpeed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temperatura wiatru słonecznego.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarAdditSolarWindTemp() As String
            Get
                Return ResourceManager.GetString("resPomiarAdditSolarWindTemp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to burza.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarBurza() As String
            Get
                Return ResourceManager.GetString("resPomiarBurza", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Burze.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarBurza_burza() As String
            Get
                Return ResourceManager.GetString("resPomiarBurza_burza", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mróz.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarBurza_mroz() As String
            Get
                Return ResourceManager.GetString("resPomiarBurza_mroz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opad.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarBurza_opad() As String
            Get
                Return ResourceManager.GetString("resPomiarBurza_opad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Trąba.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarBurza_traba() As String
            Get
                Return ResourceManager.GetString("resPomiarBurza_traba", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Upał.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarBurza_upal() As String
            Get
                Return ResourceManager.GetString("resPomiarBurza_upal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wiatr.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarBurza_wiatr() As String
            Get
                Return ResourceManager.GetString("resPomiarBurza_wiatr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Przewidywany na.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarNoaaKindexPredicted() As String
            Get
                Return ResourceManager.GetString("resPomiarNoaaKindexPredicted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opad.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarOpad() As String
            Get
                Return ResourceManager.GetString("resPomiarOpad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Punkt rosy.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarRosa() As String
            Get
                Return ResourceManager.GetString("resPomiarRosa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WtrSł gęstość.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarSolarWindDensity() As String
            Get
                Return ResourceManager.GetString("resPomiarSolarWindDensity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WtrSł szybk.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarSolarWindSpeed() As String
            Get
                Return ResourceManager.GetString("resPomiarSolarWindSpeed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WtrSł temp.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarSolarWindTemp() As String
            Get
                Return ResourceManager.GetString("resPomiarSolarWindTemp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Widoczność.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarWidocz() As String
            Get
                Return ResourceManager.GetString("resPomiarWidocz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wiatr.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarWind() As String
            Get
                Return ResourceManager.GetString("resPomiarWind", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zachmurzenie.
        '''</summary>
        Friend Shared ReadOnly Property resPomiarZachm() As String
            Get
                Return ResourceManager.GetString("resPomiarZachm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Średnia 24 godzinna.
        '''</summary>
        Friend Shared ReadOnly Property resRAHdailyAvg() As String
            Get
                Return ResourceManager.GetString("resRAHdailyAvg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zapisz.
        '''</summary>
        Friend Shared ReadOnly Property resSaveFav() As String
            Get
                Return ResourceManager.GetString("resSaveFav", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to suma wszystkich.
        '''</summary>
        Friend Shared ReadOnly Property resSeismicEU_All() As String
            Get
                Return ResourceManager.GetString("resSeismicEU_All", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to wszystkie.
        '''</summary>
        Friend Shared ReadOnly Property resSeismicEU_DistAll() As String
            Get
                Return ResourceManager.GetString("resSeismicEU_DistAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to domowego miesięcznego zużycia.
        '''</summary>
        Friend Shared ReadOnly Property resSeismicEU_HomekWh() As String
            Get
                Return ResourceManager.GetString("resSeismicEU_HomekWh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Miesięczne zużycie w Twoim domu.
        '''</summary>
        Friend Shared ReadOnly Property resSeismicEU_HomekWh_Hdr() As String
            Get
                Return ResourceManager.GetString("resSeismicEU_HomekWh_Hdr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to miesięcznej produkcji krajowej.
        '''</summary>
        Friend Shared ReadOnly Property resSeismicEU_KrajTWh() As String
            Get
                Return ResourceManager.GetString("resSeismicEU_KrajTWh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Roczna produkcja krajowa.
        '''</summary>
        Friend Shared ReadOnly Property resSeismicEU_KrajTWh_Hdr() As String
            Get
                Return ResourceManager.GetString("resSeismicEU_KrajTWh_Hdr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to jedno najsilniejsze.
        '''</summary>
        Friend Shared ReadOnly Property resSeismicEU_Max() As String
            Get
                Return ResourceManager.GetString("resSeismicEU_Max", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zasięg.
        '''</summary>
        Friend Shared ReadOnly Property resSeismicEU_SldHdr() As String
            Get
                Return ResourceManager.GetString("resSeismicEU_SldHdr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to T odczuwana.
        '''</summary>
        Friend Shared ReadOnly Property resTempOdczuwana() As String
            Get
                Return ResourceManager.GetString("resTempOdczuwana", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to wysokość.
        '''</summary>
        Friend Shared ReadOnly Property resWysokosc() As String
            Get
                Return ResourceManager.GetString("resWysokosc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to świat.
        '''</summary>
        Friend Shared ReadOnly Property uiZasieg0() As String
            Get
                Return ResourceManager.GetString("uiZasieg0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Europa.
        '''</summary>
        Friend Shared ReadOnly Property uiZasieg1() As String
            Get
                Return ResourceManager.GetString("uiZasieg1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Polska.
        '''</summary>
        Friend Shared ReadOnly Property uiZasieg2() As String
            Get
                Return ResourceManager.GetString("uiZasieg2", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
